// <auto-generated />
using System;
using DatacampAICoordinator.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatacampAICoordinator.Infrastructure.Data.Migrations
{
    [DbContext(typeof(DatacampDbContext))]
    [Migration("20251031180257_UpdatedDbModel")]
    partial class UpdatedDbModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("DatacampAICoordinator.Infrastructure.Models.Process", b =>
                {
                    b.Property<int>("ProcessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfRun")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FinalDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InitialDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("RecordsProcessed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ProcessId");

                    b.HasIndex("DateOfRun");

                    b.HasIndex("InitialDate", "FinalDate");

                    b.ToTable("Process");
                });

            modelBuilder.Entity("DatacampAICoordinator.Infrastructure.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DatacampId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Slug");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("DatacampAICoordinator.Infrastructure.Models.StudentDailyStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Chapters")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Courses")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastXpDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProcessId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Xp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StudentId", "Date");

                    b.ToTable("StudentDailyStatus");
                });

            modelBuilder.Entity("DatacampAICoordinator.Infrastructure.Models.StudentProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DifferenceOfChapters")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DifferenceOfCourses")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DifferenceOfXp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProcessId");

                    b.HasIndex("StudentId", "ProcessId");

                    b.ToTable("StudentProgress");
                });

            modelBuilder.Entity("DatacampAICoordinator.Infrastructure.Models.StudentDailyStatus", b =>
                {
                    b.HasOne("DatacampAICoordinator.Infrastructure.Models.Student", "Student")
                        .WithMany("DailyStatuses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DatacampAICoordinator.Infrastructure.Models.StudentProgress", b =>
                {
                    b.HasOne("DatacampAICoordinator.Infrastructure.Models.Process", "Process")
                        .WithMany("ProgressRecords")
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatacampAICoordinator.Infrastructure.Models.Student", "Student")
                        .WithMany("ProgressRecords")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Process");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DatacampAICoordinator.Infrastructure.Models.Process", b =>
                {
                    b.Navigation("ProgressRecords");
                });

            modelBuilder.Entity("DatacampAICoordinator.Infrastructure.Models.Student", b =>
                {
                    b.Navigation("DailyStatuses");

                    b.Navigation("ProgressRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
